server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:5518/seata_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: xxxxxxxx
  cloud:
    nacos:
      server-addr: localhost:8850
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
seata:
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8850
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-tc-server
      username: nacos
      password: nacos
  tx-service-group: seata-demo # 事务组名称
#  service:
#    vgroup-mapping: # 事务组与cluster的映射关系
#      seata-demo: SH
  data-source-proxy-mode: AT
  config:
    type: nacos
    nacos:
      server-addr: localhost:8850
      username: nacos
      password: nacos
      group: SEATA_GROUP
      data-id: client.properties